const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const overlay=$('#overlay'),title=$('#toolTitle'),body=$('#toolBody'); let current=[];
function menu(id){$('#'+id)?.classList.toggle('open')}
$$('[data-menu]').forEach(x=>x.onclick=e=>{e.stopPropagation(); $$('.mega').forEach(m=>m.classList.remove('open'));menu(x.dataset.menu)});
$$('.navdrop').forEach(x=>x.onclick=e=>{e.stopPropagation();menu(x.dataset.menu)});
document.addEventListener('click',e=>{if(!e.target.closest('.mega')&&!e.target.closest('.navdrop')&&!e.target.closest('[data-menu]'))$$('.mega').forEach(m=>m.classList.remove('open'))});
$$('[data-tool]').forEach(x=>x.onclick=()=>openTool(x.dataset.tool)); $('#close').onclick=()=>overlay.classList.remove('open');
const names={merge:'Merge PDF',split:'Split PDF',delete:'Delete PDF Pages',extract:'Extract PDF Pages',compress:'Compress PDF',jpgpdf:'JPG to PDF',pdfjpg:'PDF to JPG',rotate:'Rotate PDF',watermark:'Add PDF Watermark',numbers:'Add Page Numbers',crop:'Crop PDF',pdftext:'PDF to Text',ocr:'OCR PDF'};
function openTool(t){$$('.mega').forEach(m=>m.classList.remove('open'));title.textContent=names[t]||'PDF Tool';body.innerHTML=template(t);overlay.classList.add('open');bindTool(t)}
function uploader(id,multiple=true,accept='application/pdf'){return `<div class="dropzone" id="${id}"><div class="up">↑</div><h3>Drop ${multiple?'files':'a file'} here</h3><p>or choose from your device</p><label class="choose">Choose ${multiple?'files':'file'}<input class="input" id="${id}Input" type="file" accept="${accept}" ${multiple?'multiple':''}></label></div><div class="filelist" id="${id}List"></div>`}
function template(t){
 if(t==='merge')return `<div class="content">${uploader('merge',true)}<div class="controls"><label>Output name <input id="outname" value="merged.pdf"></label></div><button class="action" id="go" disabled>Merge PDFs</button><div id="status"></div></div>`;
 if(t==='split'||t==='extract')return `<div class="content">${uploader('pdf',false)}<div class="controls"><label>Pages <input id="pages" placeholder="1-3,5,8-10"></label></div><button class="action" id="go" disabled>${t==='split'?'Split PDF':'Extract Pages'}</button><div id="status"></div></div>`;
 if(t==='delete')return `<div class="content">${uploader('pdf',false)}<div class="controls"><label>Pages to delete <input id="pages" placeholder="2,4,7-9"></label></div><button class="action" id="go" disabled>Delete Pages</button><div id="status"></div></div>`;
 if(t==='jpgpdf')return `<div class="content">${uploader('images',true,'image/*')}<div class="controls"><label>Page <select id="size"><option>A4</option><option>Letter</option><option>Fit to image</option></select></label><label>Margin <input id="margin" type="number" value="20"></label><label>Quality <select id="quality"><option value="0.8">Standard</option><option value="1" selected>High</option></select></label></div><button class="action" id="go" disabled>Create PDF</button><div id="status"></div></div>`;
 if(t==='pdfjpg')return `<div class="content">${uploader('pdf',false)}<div class="controls"><label>Scale <select id="scale"><option value="1">100%</option><option value="1.5" selected>150%</option><option value="2">200%</option></select></label><label>Format <select id="fmt"><option value="image/jpeg">JPG</option><option value="image/png">PNG</option></select></label></div><button class="action" id="go" disabled>Convert PDF</button><div id="status"></div></div>`;
 if(t==='rotate')return `<div class="content">${uploader('pdf',false)}<div class="controls"><label>Rotation <select id="deg"><option>90</option><option>180</option><option>270</option></select></label></div><button class="action" id="go" disabled>Rotate PDF</button><div id="status"></div></div>`;
 if(t==='watermark')return `<div class="content">${uploader('pdf',false)}<div class="controls"><label>Text <input id="wt" value="FILEFORGE"></label><label>Size <input id="ws" type="number" value="36"></label><label>Opacity <input id="wo" type="number" min="0.05" max="1" step=".05" value=".25"></label><label>Angle <input id="wa" type="number" value="-35"></label></div><button class="action" id="go" disabled>Add Watermark</button><div id="status"></div></div>`;
 if(t==='numbers')return `<div class="content">${uploader('pdf',false)}<div class="controls"><label>Position <select id="pos"><option value="bc">Bottom center</option><option value="br">Bottom right</option><option value="bl">Bottom left</option><option value="tc">Top center</option></select></label><label>Start <input id="start" type="number" value="1"></label><label>Size <input id="ns" type="number" value="12"></label></div><button class="action" id="go" disabled>Add Page Numbers</button><div id="status"></div></div>`;
 if(t==='crop')return `<div class="content">${uploader('pdf',false)}<div class="controls"><label>Crop % <input id="cropPct" type="number" min="0" max="40" value="5"></label></div><button class="action" id="go" disabled>Crop PDF</button><div id="status"></div></div>`;
 if(t==='compress')return `<div class="content">${uploader('pdf',false)}<div class="controls"><label>Quality <select id="cq"><option value="0.45">Small</option><option value="0.65" selected>Balanced</option><option value="0.82">High</option></select></label><label>Render scale <select id="cs"><option value="1">1×</option><option value="1.25" selected>1.25×</option><option value="1.5">1.5×</option></select></label></div><p class="status">This mode rebuilds each page as a JPEG image. Text/searchability may be lost, but the output is a real reduced-size PDF.</p><button class="action" id="go" disabled>Reduce PDF Size</button><div id="status"></div></div>`;
 if(t==='pdftext')return `<div class="content">${uploader('pdf',false)}<button class="action" id="go" disabled>Extract Text</button><textarea id="result" style="width:100%;height:300px;margin-top:15px;padding:12px;border:1px solid #ddd;border-radius:8px"></textarea><div id="status"></div></div>`;
 if(t==='ocr')return `<div class="content">${uploader('pdf',false)}<div class="status">OCR uses a large browser library and may take time on mobile. The PDF is rendered page-by-page and recognized locally when Tesseract.js is available.</div><button class="action" id="go" disabled>Start OCR</button><textarea id="result" style="width:100%;height:280px;margin-top:15px;padding:12px;border:1px solid #ddd;border-radius:8px"></textarea><div id="status"></div></div>`;
 return `<div class="content"><div class="status"><b>${names[t]||'Tool'}</b> is listed in the advanced menu. This starter keeps unsupported operations honest instead of producing fake files.</div></div>`;
}
function parsePages(s,max,zero=false){const set=new Set();for(const part of (s||'').split(',').map(x=>x.trim()).filter(Boolean)){if(part.includes('-')){let[a,b]=part.split('-').map(Number);if(a>b)[a,b]=[b,a];for(let i=a;i<=b;i++)if(i>=1&&i<=max)set.add(zero?i-1:i)}else{let n=Number(part);if(n>=1&&n<=max)set.add(zero?n-1:n)}}return [...set]}
function setup(id,cb){const z=$('#'+id),inp=$('#'+id+'Input');const files=f=>{current=[...f];renderFiles(id,current);cb(current)};inp.onchange=e=>files(e.target.files);['dragenter','dragover'].forEach(v=>z.addEventListener(v,e=>{e.preventDefault();z.classList.add('drag')}));['dragleave','drop'].forEach(v=>z.addEventListener(v,e=>{e.preventDefault();z.classList.remove('drag')}));z.ondrop=e=>files(e.dataTransfer.files)}
function renderFiles(id,fs){const el=$('#'+id+'List');if(el)el.innerHTML=fs.map((f,i)=>`<div class="file"><span>${i+1}. ${esc(f.name)}</span><span>${size(f.size)}</span></div>`).join('')}
function size(n){return n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(2)+' MB'} function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function status(x){$('#status').innerHTML=`<div class="status">${x}</div>`} function enable(){const b=$('#go');if(b)b.disabled=false} function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)} function pdfBlob(bytes){return new Blob([bytes],{type:'application/pdf'})}
async function loadPdf(f){return PDFLib.PDFDocument.load(await f.arrayBuffer())}
async function renderPdfPage(f,n,scale=1){const data=await f.arrayBuffer(),pdf=await pdfjsLib.getDocument({data}).promise,p=await pdf.getPage(n),v=p.getViewport({scale}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;return {pdf,p,c,v}}
function bindTool(t){
 if(['merge'].includes(t)){setup('merge',()=>enable());$('#go').onclick=async()=>{status('Merging…');const out=await PDFLib.PDFDocument.create();for(const f of current){const src=await loadPdf(f);const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p))}download(pdfBlob(await out.save()),$('#outname').value||'merged.pdf');status('Done. Your merged PDF was downloaded.')};return}
 if(['split','extract','delete'].includes(t)){setup('pdf',()=>enable());$('#go').onclick=async()=>{const src=await loadPdf(current[0]),n=src.getPageCount(),selected=parsePages($('#pages').value,n,true);if(!selected.length){status('Enter page numbers such as 1-3,5.');return}const out=await PDFLib.PDFDocument.create();let ids=t==='delete'?src.getPageIndices().filter(i=>!selected.includes(i)):selected;const pages=await out.copyPages(src,ids);pages.forEach(p=>out.addPage(p));download(pdfBlob(await out.save()),t+'.pdf');status(`Done. ${pages.length} page(s) exported.`)};return}
 if(t==='jpgpdf'){setup('images',()=>enable());$('#go').onclick=async()=>{status('Creating PDF…');const out=await PDFLib.PDFDocument.create(),m=Math.max(0,Number($('#margin').value)||0),sizeSel=$('#size').value;for(const f of current){const b=await f.arrayBuffer();let im;if(f.type==='image/png')im=await out.embedPng(b);else im=await out.embedJpg(b);let w=im.width+2*m,h=im.height+2*m;if(sizeSel==='A4'){w=595;h=842}if(sizeSel==='Letter'){w=612;h=792}const page=out.addPage([w,h]);const scale=Math.min((w-2*m)/im.width,(h-2*m)/im.height);page.drawImage(im,{x:(w-im.width*scale)/2,y:(h-im.height*scale)/2,width:im.width*scale,height:im.height*scale})}download(pdfBlob(await out.save()),'images-to-pdf.pdf');status('Done. Images converted to PDF.')};return}
 if(t==='pdfjpg'){setup('pdf',()=>enable());$('#go').onclick=async()=>{status('Rendering PDF pages…');if(!window.JSZip)await loadScript('https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js');const data=await current[0].arrayBuffer(),pdf=await pdfjsLib.getDocument({data}).promise,zip=new JSZip(),fmt=$('#fmt').value,ext=fmt==='image/png'?'png':'jpg';for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n),v=p.getViewport({scale:Number($('#scale').value)}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const blob=await new Promise(r=>c.toBlob(r,fmt,.92));zip.file(`page-${n}.${ext}`,await blob.arrayBuffer())}download(await zip.generateAsync({type:'blob'}),'pdf-pages.zip');status(`Done. ${pdf.numPages} page(s) packed into a ZIP.`)};return}
 if(t==='rotate'){setup('pdf',()=>enable());$('#go').onclick=async()=>{const p=await loadPdf(current[0]),d=Number($('#deg').value);p.getPages().forEach(x=>x.setRotation(PDFLib.degrees((x.getRotation().angle+d)%360)));download(pdfBlob(await p.save()),'rotated.pdf');status('Done. Pages rotated.')};return}
 if(t==='watermark'){setup('pdf',()=>enable());$('#go').onclick=async()=>{const p=await loadPdf(current[0]),font=await p.embedFont(PDFLib.StandardFonts.HelveticaBold),text=$('#wt').value||'FILEFORGE',sz=Number($('#ws').value)||36,op=Math.min(1,Math.max(.05,Number($('#wo').value)||.25)),angle=Number($('#wa').value)||-35;p.getPages().forEach(pg=>{const {width,height}=pg.getSize();const tw=font.widthOfTextAtSize(text,sz);pg.drawText(text,{x:(width-tw)/2,y:height/2,size:sz,font,color:PDFLib.rgb(.86,.12,.12),opacity:op,rotate:PDFLib.degrees(angle)})});download(pdfBlob(await p.save()),'watermarked.pdf');status('Done. Watermark added.')};return}
 if(t==='numbers'){setup('pdf',()=>enable());$('#go').onclick=async()=>{const p=await loadPdf(current[0]),font=await p.embedFont(PDFLib.StandardFonts.HelveticaBold),sz=Number($('#ns').value)||12,start=Number($('#start').value)||1,position=$('#pos').value;p.getPages().forEach((pg,i)=>{const {width,height}=pg.getSize(),txt=String(start+i),tw=font.widthOfTextAtSize(txt,sz);let x=(width-tw)/2,y=18;if(position==='br'){x=width-tw-18}if(position==='bl'){x=18}if(position==='tc'){y=height-sz-12}pg.drawText(txt,{x,y,size:sz,font,color:PDFLib.rgb(.15,.15,.18)})});download(pdfBlob(await p.save()),'numbered.pdf');status('Done. Page numbers added.')};return}
 if(t==='crop'){setup('pdf',()=>enable());$('#go').onclick=async()=>{const p=await loadPdf(current[0]),pct=Math.min(40,Math.max(0,Number($('#cropPct').value)||0))/100;p.getPages().forEach(pg=>{const {width,height}=pg.getSize(),x=width*pct,y=height*pct;pg.setCropBox(x,y,width-2*x,height-2*y)});download(pdfBlob(await p.save()),'cropped.pdf');status('Done. Crop box applied.')};return}
 if(t==='compress'){setup('pdf',()=>enable());$('#go').onclick=async()=>{try{const src=current[0],data=await src.arrayBuffer(),pdf=await pdfjsLib.getDocument({data}).promise,out=await PDFLib.PDFDocument.create(),scale=Number($('#cs').value),quality=Number($('#cq').value);status('Rendering pages for compression…');for(let n=1;n<=pdf.numPages;n++){status(`Compressing page ${n} of ${pdf.numPages}…`);const pg=await pdf.getPage(n),v=pg.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await pg.render({canvasContext:c.getContext('2d'),viewport:v,background:'white'}).promise;const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',quality)),bytes=await blob.arrayBuffer(),im=await out.embedJpg(bytes);const view=pg.getViewport({scale:1}),page=out.addPage([view.width,view.height]);page.drawImage(im,{x:0,y:0,width:view.width,height:view.height})}const bytes=await out.save({useObjectStreams:true});download(pdfBlob(bytes),'compressed.pdf');status(`Done. Original ${size(src.size)} → compressed ${size(bytes.length)}.`)}catch(e){console.error(e);status('Compression failed. Please try a smaller PDF.')}};return}
 if(t==='pdftext'){setup('pdf',()=>enable());$('#go').onclick=async()=>{status('Extracting text…');const data=await current[0].arrayBuffer(),pdf=await pdfjsLib.getDocument({data}).promise;let out='';for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),c=await page.getTextContent();out+=`\n--- Page ${n} ---\n`+c.items.map(x=>x.str).join(' ')+'\n'}$('#result').value=out.trim();status('Done. Text extracted.')};return}
 if(t==='ocr'){setup('pdf',()=>enable());$('#go').onclick=async()=>{status('Loading OCR engine…');if(!window.Tesseract){await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js')}const data=await current[0].arrayBuffer(),pdf=await pdfjsLib.getDocument({data}).promise,worker=await Tesseract.createWorker('eng');let out='';for(let n=1;n<=pdf.numPages;n++){status(`OCR page ${n} of ${pdf.numPages}…`);const p=await pdf.getPage(n),v=p.getViewport({scale:1.5}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const r=await worker.recognize(c);out+=`\n--- Page ${n} ---\n${r.data.text}\n`}await worker.terminate();$('#result').value=out.trim();status('OCR complete. Copy the extracted text below.')} }
}
function loadScript(src){return new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
